# Generated by Django 4.2.3 on 2023-11-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=32, verbose_name="邮箱")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=32, verbose_name="书名")),
                ("author", models.CharField(max_length=64, verbose_name="作者")),
                ("type", models.CharField(max_length=64, verbose_name="类型")),
                ("genre", models.CharField(max_length=64, verbose_name="主题")),
                ("brief", models.TextField(blank=True, verbose_name="简介")),
                ("comment", models.TextField(blank=True, verbose_name="评论")),
            ],
        ),
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.CharField(max_length=32, verbose_name="邮箱")),
                ("password", models.CharField(max_length=64, verbose_name="密码")),
            ],
        ),
    ]
